-- MySQL Script generated by MySQL Workbench
-- Sun Nov  3 20:59:11 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema banco
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `banco` DEFAULT CHARACTER SET utf8 ;
USE banco ;

-- -----------------------------------------------------
-- Table `banco`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `banco`.`cliente` (
  `idCliente` INT NOT NULL AUTO_INCREMENT,
  `nomeCliente` VARCHAR(75) NOT NULL,
  `cpfCliente` VARCHAR(11) NOT NULL,
  `dataNiver` DATE NOT NULL,
  `enderecoCliente` VARCHAR(100) NOT NULL,
  `emailCliente` VARCHAR(45) NOT NULL,
  `senha` VARCHAR(255) NOT NULL, -- Adicionado campo para senha
  PRIMARY KEY (`idCliente`),
  UNIQUE INDEX `idClient_UNIQUE` (`idCliente` ASC),
  UNIQUE INDEX `cpfCliente_UNIQUE` (`cpfCliente` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `banco`.`conta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `banco`.`conta` (
  `numeroConta` INT NOT NULL AUTO_INCREMENT,
  `cliente_idCliente` INT NOT NULL,
  `agenciaConta` VARCHAR(4) NOT NULL,
  `saldoConta` DECIMAL(14,2) NOT NULL,
  `emprestimoConta` DECIMAL(14,2) NOT NULL,
  `emprestimoRetirado` DECIMAL(14,2) NOT NULL,
  PRIMARY KEY (`numeroConta`, `cliente_idCliente`),
  UNIQUE INDEX `numeroConta_UNIQUE` (`numeroConta` ASC),
  INDEX `fk_conta_cliente_idx` (`cliente_idCliente` ASC),
  CONSTRAINT `fk_conta_cliente`
    FOREIGN KEY (`cliente_idCliente`)
    REFERENCES `banco`.`cliente` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `banco`.`cartaCredito`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `banco`.`cartaCredito` (
  `idcartaCredito` INT NOT NULL AUTO_INCREMENT,
  `conta_numeroConta` INT NOT NULL,
  `conta_cliente_idCliente` INT NOT NULL,
  `creditoDisponivel` DECIMAL(14,2) NOT NULL,
  `creditoRetirado` DECIMAL(14,2) NOT NULL,
  `nmrCartao` VARCHAR(16) NOT NULL,
  `nmrSeguranca` VARCHAR(3) NOT NULL,
  PRIMARY KEY (`idcartaCredito`, `conta_numeroConta`, `conta_cliente_idCliente`),
  UNIQUE INDEX `idcartaCredito_UNIQUE` (`idcartaCredito` ASC),
  INDEX `fk_cartaCredito_conta1_idx` (`conta_numeroConta` ASC, `conta_cliente_idCliente` ASC),
  UNIQUE INDEX `nmrCartao_UNIQUE` (`nmrCartao` ASC),
  UNIQUE INDEX `nmrSeguranca_UNIQUE` (`nmrSeguranca` ASC),
  CONSTRAINT `fk_cartaCredito_conta1`
    FOREIGN KEY (`conta_numeroConta`, `conta_cliente_idCliente`)
    REFERENCES `banco`.`conta` (`numeroConta`, `cliente_idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `banco`.`extrato`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `banco`.`extrato` (
  `idExtrato` INT NOT NULL AUTO_INCREMENT,
  `valorExtrato` DECIMAL(14,2) NOT NULL,
  `descricaoExtrato` VARCHAR(40) NOT NULL,
  `conta_numeroConta` INT NOT NULL,
  `conta_cliente_idCliente` INT NOT NULL,
  PRIMARY KEY (`idExtrato`, `conta_numeroConta`, `conta_cliente_idCliente`),
  UNIQUE INDEX `idextrato_UNIQUE` (`idExtrato` ASC),
  INDEX `fk_extrato_conta1_idx` (`conta_numeroConta` ASC, `conta_cliente_idCliente` ASC),
  CONSTRAINT `fk_extrato_conta1`
    FOREIGN KEY (`conta_numeroConta`, `conta_cliente_idCliente`)
    REFERENCES `banco`.`conta` (`numeroConta`, `cliente_idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
